name: scriny
description: "A tiny scripting language for Dart. Also supports evaluating simple math expressions."
version: 0.3.1
homepage: https://github.com/Skyost/Scriny
repository: https://github.com/Skyost/Scriny
issue_tracker: https://github.com/Skyost/Scriny/issues
funding:
  - https://ko-fi.com/Skyost
  - https://paypal.me/Skyost
executables:
  scriny:

environment:
  sdk: ^3.8.1

dependencies:
  petitparser: '>=6.1.0 <=7.0.0'
  args: ^2.7.0
  meta: '>=1.16.0 <2.0.0'

dev_dependencies:
  test: any
  flutter_lints: ^6.0.0
  release: ^0.1.5

release:
  changelog:
    header: '# 📰 Scriny changelog'
    defaultIgnoredScopes: ['docs', 'version', 'deps', 'test']
